#!/bin/env bash

# Date
date=$(date "+%F")

# Clock
time=$(date "+%H:%M")

# Battery
bat_file=/sys/class/power_supply/BAT0/capacity
if [ -f $bat_file ]; then
    bat_cap=$(cat $bat_file)
else
    bat_cap="N/A"
fi

# Volume
if command -v wpctl > /dev/null; then
    volume="$(wpctl get-volume @DEFAULT_AUDIO_SINK@\
        | cut -d " " -f 2\
        | cut -d "." -f 2)"
else
    volume="N/A"
fi

# Brightness
if command -v brightnessctl > /dev/null; then
    brightness=$(brightnessctl get)
else
    brightness="N/A"
fi
export CC

echo -e "Brightness: $brightness\
    Battery: $bat_cap\
    Volume: $volume\
    Date: $date\
    Time: $time"
