#!/bin/env bash

# Date
date="$(date "+%F %H:%M")"

# Battery
bat_file=/sys/class/power_supply/BAT0/capacity
if [ -f $bat_file ]; then
    bat_cap="Battery: $(cat $bat_file)"
else
    bat_cap=""
fi

# Volume
if command -v wpctl > /dev/null; then
    volume="Volume: $(wpctl get-volume @DEFAULT_AUDIO_SINK@\
        | cut -d " " -f 2\
        | cut -d "." -f 2)"
else
    volume=""
fi

# Brightness
if command -v brightnessctl > /dev/null; then
    brightness="Brightness: $(brightnessctl get)"
else
    brightness=""
fi

echo -e "\
    $brightness\
    $bat_cap\
    $volume\
    $date"
