#!/usr/bin/env bash

# Script must be run from inside it's directory
if [ ! -f "$(basename "$0")" ]; then
    echo "Script must be run from inside it's directory"
    exit 1
fi

# Set config directory
if [[ -z "${XDG_CONFIG_HOME}" ]]; then
    config_dir="$HOME/.config"
else
    config_dir="${XDG_CONFIG_HOME}"
fi
# Set bin directory
bin_dir="$HOME/.local/bin"
# Set font directory
font_dir="$HOME/.local/share/fonts"

# Create config directory if missing
mkdir -p $config_dir
# Create bin directory if missing
mkdir -p $bin_dir
# Create font directory if missing
mkdir -p $font_dir

# Fonts
echo "Installing fonts..."
cp $PWD/fonts/* $font_dir

# Foot
echo "Installing foot..."
ln -snf $PWD/foot $config_dir/

# Bash
echo "Installing bash..."
ln -snf $PWD/bash/.bash_profile $HOME/
ln -snf $PWD/bash/.bashrc $HOME/

# Git
echo "Installing git..."
ln -snf $PWD/git $config_dir/

# Neovim
echo "Installing neovim..."
ln -snf $PWD/nvim $config_dir/

# Sway
echo "Installing sway..."
ln -snf $PWD/sway $config_dir/

# Tmux
echo "Installing tmux..."
if ! command -v fzf &>/dev/null; then
    echo -e "\tdependency: fzf not found";
fi
ln -snf $PWD/tmux $config_dir/
ln -snf $PWD/tmux/txs $HOME/.local/bin/

# Emacs
echo "Installing emacs..."
ln -snf $PWD/emacs $config_dir/

# GDB
echo "Installing gdb..."
ln -snf $PWD/gdb $config_dir/

# Mail
## Deps:
##      mbsync
##      msmtp
##      notmuch
##      systemd file
