#!/usr/bin/env bash

# Script must be run from inside it's directory
if [ ! -f "$(basename "$0")" ]; then
    echo "Script must be run from inside it's directory"
    exit 1
fi

# Set config directory
if [[ -z "${XDG_CONFIG_HOME}" ]]; then
    config_dir="$HOME/.config"
else
    config_dir="${XDG_CONFIG_HOME}"
fi
# Set bin directory
bin_dir="$HOME/.local/bin"
# Set font directory
font_dir="$HOME/.local/share/fonts"

# Create config directory if missing
mkdir -p $config_dir
# Create bin directory if missing
mkdir -p $bin_dir
# Create font directory if missing
mkdir -p $font_dir

# Fonts
# cp $PWD/res/fonts/* $font_dir

# Foot
ln -snf $PWD/foot $config_dir/

# Bash
ln -snf $PWD/bash/.bash_profile $HOME/
ln -snf $PWD/bash/.bashrc $HOME/

# Git
ln -snf $PWD/git $config_dir/

# Mail
# TODO

# Neovim
ln -snf $PWD/nvim $config_dir/

# Sway
ln -snf $PWD/sway $config_dir/

# Tmux
ln -snf $PWD/tmux $config_dir/
ln -snf $PWD/tmux/txs $HOME/.local/bin/

# Emacs
ln -snf $PWD/emacs $config_dir/
